### ISSUE TITLE
トップページのスライダー実装について

### ISSUE THREAD

**Issue by stmngw** [mofmof/site#1]

**Comment by stmngw** [comment]
ナビゲーションのカレント表示の実装がまだ。
slickで実現可能か検討中。

**Comment by stmngw** [comment]
@harada4atsushi @maru877 
トップページのメインビジュアル部分のスライダー実装が終わりましたので、レビューお願いできますでしょうか。デザイン指示ですとPCの際はautoplayということだったので、そのようにしてありますが、ちょっとうるさい気もします。SPはautoplayをfalseにしています。

アニメーションがあるともう少しよくなるかと思いますが、現状あまりイケテナイ感じかと。。。
いかがでしょうか？FBお願いします。

**Comment by stmngw** [comment]
@harada4atsushi @maru877 
確認用URLはこちらです。よろしくお願いいたします。
http://mof.stm.me/

**Comment by maru877** [comment]
@stmngw スライダー問題ありません。有り難う御座います。
全体のフィードバックはこちらで行います。
https://github.com/mofmof/site/issues/13

**Comment by stmngw** [comment]
対応済み
