### ISSUE TITLE
全体デザインレビュー

### ISSUE THREAD

**Issue by stmngw** [mofmof/site#13]

**Comment by stmngw** [comment]
http://mof.stm.me/

**Comment by maru877** [comment]
もろもろご対応頂きまして、有り難うございます。
下記、レビュー結果です。(スコープ外のものもあるかもしれません。その場合は遠慮なく教えてください)

- 共通
  - ボタンのホバー時の変化はトップページの"サービス"に統一してほしい
  - フッターのSNSリンクがtwitterとfacebook２つ同時に反応する
  - グローバルナビのアニメーションは不要です。常に表示させたいです。
  - スマホレイアウトに切り替わるブレークポイントが1024pxなので広すぎる（通常は768px）
  - カルーセルがスマホの広めの横幅で左にずれる
- スマホ
  - スクロールできない(タッチアップになっている？スクロールがキャンセルされていない)
- http://mof.stm.me/
  - MERITのホバーは不要です。
  - MERITのホバー時に別のアイテムのボタンも反応している
- http://mof.stm.me/about/
  - 誤字 mofmoとは
  - 原田さんのfacebookとtwitterのアイコン部分が透明になっている
  - INFORMATIONの下の「mofmofのお知らせ」の文字が小さい
  - INFORMATIONの下にMOREボタンがない
- http://mof.stm.me/service/
  - 悩み・特徴のボックスが1300〜1024pxではみ出す
- http://mof.stm.me/recruit/
  - 応募するボタンの位置がデザインと異なる
- http://mof.stm.me/interview/
  - INTERVIEW.0.5がデッドリンク
- http://mof.stm.me/contact/
  - 問い合わせページには問い合わせリンクは不要
- http://mof.stm.me/interview/dialog/dialog01.html
  - クライアントプロフィールの写真が鐘ヶ江さんではなく緒方さんになっている

こちらは、野川さんのスコープ外かもしれませんが一応共有しておきます。

- 共通
  - h1にテキストが入っていない
  - imgにaltが入っていない
- スマホ
  - スマホのグローバルメニューが凄く縦長
  - スマホのハンバーガーボタンのクリックできる範囲が狭い
- http://mof.stm.me/about/
  - メンバーのマークアップはfigureを使う
- http://mof.stm.me/service/
  - スマホの広めの横幅で画像が拡大しすぎてぼやける

宜しくお願いいたします。

**Comment by stmngw** [comment]
>共通

>>ボタンのホバー時の変化はトップページの"サービス"に統一してほしい

【質問】  
meritも同様にボタンと中のテキストのみ色が変わるのでよいでしょうか？

>>スマホレイアウトに切り替わるブレークポイントが1024pxなので広すぎる（通常は768px）

【質問】  
メッセージでもお伝えしましたが、デザインのご指示がタブレットのランドスケープということでした。
おそらくデザインのオーダーもPCユーザーを重視ということだったのではないかと思われます。またブレークポイントは一つであり、デザイン的にもグリッドシステムはマッチしないと判断し採用しませんでしたので、今から768pxより手前のサイズまでを崩れがない様に実装するのは、技術的にはともかく、時間的には厳しいです。個人的には、ブレイクポイントは2つが理想と考えますが、その際は通常コストを考えてグリッドシステムを採用します。（私がデザインする場合はですが。。。）本来、望ましいのは768pxでしょうか？その様でしたら全面的に構造の見直しが必要です。


>スマホ

>>クロールできない(タッチアップになっている？スクロールがキャンセルされていない)

【質問】  
こちらについては、リンクをタップしたと判定されるため別画面へ遷移するということでしょうか？もしそのようでしたら、PCの際、ホバー時の効果のデザイン指示が多くあるため、aタグをエリアに指定しているのですが、リンクをボタンやテキストのみにするとすると誤動作は防げるようになるかと思いますがいかがでしょうか？

>>MERITのホバーは不要です。
>>MERITのホバー時に別のアイテムのボタンも反応している

【質問】 
上記とも関連しますが、PCでのホバー効果も必要でしょうか？共通の部分でのご指示は"サービス"に統一としていただいてますので、それにならってよろしいでしょうか？


>>悩み・特徴のボックスが1300〜1024pxではみ出す

【質問】  
デザインが1300pxの指定になっていたかと思います。デザインカンプに従うとPCのワンカラムの際のコンテナの幅は、1200px,1000px,900px,800pxの4種類ありましたが、こちらは唯一の例外になります。コンテナとして認識する中では一番大きな幅が1200pxになりますので、サイト全体としてコンテンツの中はmaxの幅が1200pxと考えてよいでしょうか？それでしたら、この部分は1200pxに収まるようにします。


>共通
>>h1にテキストが入っていない

【質問】  
ロゴにはaltを入れさせていただきますが、会社名の他サイトのディスクリプションのようなテキストも入れる様でしたらご指示ください。
セクションと見出しタグについてはデザインレビューの際に少しご指摘させていただきましたが、（デザイン上、見出しとセクショニングがわかりづらかったので）特にご指示はありませんでした。見出しレベルとセクショニングについてはご指示いただければ修正いたします。その際は構造の変更も必要になるかと思いますので、お時間いただけますようお願いいたします。

>>imgにaltが入っていない

【質問】    
こちらは、私の方で解釈して適当と思われる文字列をいれさせていただけばよろしいでしょうか？

**Comment by maru877** [comment]
【質問】
meritも同様にボタンと中のテキストのみ色が変わるのでよいでしょうか？
【回答】
その認識で合っております。

【質問】
メッセージでもお伝えしましたが、デザインのご指示がタブレットのランドスケープということでした。
おそらくデザインのオーダーもPCユーザーを重視ということだったのではないかと思われます。またブレークポイントは一つであり、デザイン的にもグリッドシステムはマッチしないと判断し採用しませんでしたので、今から768pxより手前のサイズまでを崩れがない様に実装するのは、技術的にはともかく、時間的には厳しいです。個人的には、ブレイクポイントは2つが理想と考えますが、その際は通常コストを考えてグリッドシステムを採用します。（私がデザインする場合はですが。。。）本来、望ましいのは768pxでしょうか？その様でしたら全面的に構造の見直しが必要です。
【回答】
こちらはPCユーザ重視ということで、対応不要です。

【質問】
こちらについては、リンクをタップしたと判定されるため別画面へ遷移するということでしょうか？もしそのようでしたら、PCの際、ホバー時の効果のデザイン指示が多くあるため、aタグをエリアに指定しているのですが、リンクをボタンやテキストのみにするとすると誤動作は防げるようになるかと思いますがいかがでしょうか？
【回答】
おそらくリンクをスクロールした時にタップされたと判断され、リンク先に飛んでしまうのかと思います。普通にスクロールできればいいので、エリア指定はそのままでお願いします。
`site/js/script.js`
```js
var _touch = ('ontouchstart' in document) ? 'touchstart' : 'click';
```
`touchend`にしてみたら想定する挙動になるかと思います。

【質問】
上記とも関連しますが、PCでのホバー効果も必要でしょうか？共通の部分でのご指示は"サービス"に統一としていただいてますので、それにならってよろしいでしょうか？
【回答】
ボタンのホバーは"サービス"と同一にして頂きたいです。イメージが大きくなったり、影が入ったりするアニメーションのみ不要という意味です。

【質問】
デザインが1300pxの指定になっていたかと思います。デザインカンプに従うとPCのワンカラムの際のコンテナの幅は、1200px,1000px,900px,800pxの4種類ありましたが、こちらは唯一の例外になります。コンテナとして認識する中では一番大きな幅が1200pxになりますので、サイト全体としてコンテンツの中はmaxの幅が1200pxと考えてよいでしょうか？それでしたら、この部分は1200pxに収まるようにします。
【回答】
デザイン指定が1300pxであったのであれば、対応は不要です。

【質問】
こちらは、私の方で解釈して適当と思われる文字列をいれさせていただけばよろしいでしょうか？
【回答】
その認識で合っております。

【質問】
ロゴにはaltを入れさせていただきますが、会社名の他サイトのディスクリプションのようなテキストも入れる様でしたらご指示ください。
セクションと見出しタグについてはデザインレビューの際に少しご指摘させていただきましたが、（デザイン上、見出しとセクショニングがわかりづらかったので）特にご指示はありませんでした。見出しレベルとセクショニングについてはご指示いただければ修正いたします。その際は構造の変更も必要になるかと思いますので、お時間いただけますようお願いいたします。
【回答】
こちらは一旦確認しますので、もう少々お待ちください。

**Comment by stmngw** [comment]
https://paper.dropbox.com/doc/FB-yQ7HfNVGQVS4a8CiCal01

**Comment by maru877** [comment]
@stmngw コメント回答しました。ご確認お願いいたします。

**Comment by stmngw** [comment]
@maru877 昨日タブレット（広めのスマホサイズ）対応完了しております。ご確認お願い致します。

**Comment by maru877** [comment]
@stmngw 
もろもろ対応有り難う御座います。
下記、追記しました。ご確認お願い致します。
https://paper.dropbox.com/doc/FB-yQ7HfNVGQVS4a8CiCal01

**Comment by stmngw** [comment]
対応済み
