### ISSUE TITLE
インフォメーションテンプレート作成

### ISSUE THREAD

**Issue by stmngw** [mofmof/site#2]

**Comment by stmngw** [comment]
@maru877 
テンプレート作成用にサンプルの記事と画像をいただけますでしょうか。

**Comment by maru877** [comment]
### サンプル画像
![mtg](https://user-images.githubusercontent.com/19515445/29053857-595bddda-7c2d-11e7-964e-601f4d1a8d66.jpeg)

### サンプル記事
[サンプルテキスト.docx](https://github.com/mofmof/site/files/1206752/default.docx)

宜しくお願いします。

**Comment by stmngw** [comment]
@maru877 
すみません、この添付いただいたdocxファイルは実際のインフォーメーションの内容でしょうか？

**Comment by stmngw** [comment]
@maru877 @harada4atsushi 
あとこちらの課題の期日をお知らせいただきたくお願いいたします。

**Comment by maru877** [comment]
@stmngw
すみません。実際のインフォメーションは既存サイトにありました。
こちらです。http://www.mof-mof.co.jp/blog/my-ope-office-ainow

**Comment by stmngw** [comment]
@maru877 @harada4atsushi 
リンク拝見しました。現状のページを踏襲すると必要な要素は以下の通りになるかと思いますがいかがでしょうか。

- サイトトップへのリンク
- メインビジュアル(トップへサムネイル表示)
- 日付
- テキスト本文
- ページング

**Comment by stmngw** [comment]
@maru877 @harada4atsushi 
あとURLの指定をお願いいたします。

**Comment by maru877** [comment]
@stmngw 
必要要素は以下で大丈夫です。
- サイトトップへのリンク
- メインビジュアル(トップへサムネイル表示)
- 日付
- テキスト本文
- ページング

URLも現行サイトを踏襲して頂く感じでお願いします。

**Comment by stmngw** [comment]
@maru877 現状と同じということになりますと、/blog/以下に記事のディレクトリがありその下にindex.htmlになりますが、netlifyの方の仕様上はそれで大丈夫でしょうか？

**Comment by stmngw** [comment]
@maru877 
デザインはこちらに近い形にしてよいでしょうか？
http://mof.stm.me/interview/interview05.html

**Comment by stmngw** [comment]
@maru877 
こちらもご対応いただけるとのことなのでコメントなしで大丈夫です！

**Comment by stmngw** [comment]
対応済み
