### ISSUE TITLE
sp 募集要項余白調整

### ISSUE THREAD

**Issue by stmngw** [mofmof/site#28]

**Comment by stmngw** [comment]
https://github.com/mofmof/site/commit/f0cbdaec6755dbeb28c57e569035252a1941d7ec

**Comment by stmngw** [comment]
@harada4atsushi 
/_posts/recruit/2017-10-26-guideline.mdの方に
{% include recruit/comment.html key="minimum_viable_product" %} 
が追加されていたのですが、/recruitではなく/postsの方を使いますか？

**Comment by harada4atsushi** [comment]
@stmngw あ、重複が残ってるんですね。気づいてませんでした。とりあえずどちらでも大丈夫なのですが、ヘッダーのリンクは_postsの方を見ていたようです。

不要な方を削除していただいても良いですか？

**Comment by harada4atsushi** [comment]
あと`guiidline.html`の方を使う場合、`image`に直接CDNの絶対アドレスを入れてしまうとデプロイされるごとにURLが変わってしまうのでOGP画像が表示されなくなります。相対パスにしておいていただけると。

**Comment by stmngw** [comment]
@harada4atsushi 
私が削除漏れでしたか。。。失礼いたしました。
postsの方を残しました。
https://github.com/mofmof/site/commit/ef048276ee277bd5923caae94ae565d884eb9b1f

**Comment by stmngw** [comment]
https://github.com/mofmof/site/commit/ef048276ee277bd5923caae94ae565d884eb9b1f
