### ISSUE TITLE
github pagesの設定変更

### ISSUE THREAD

**Issue by stmngw** [mofmof/site#3]
@harada4atsushi @maru877 

http://tech.mof-mof.co.jp/site/でjekyllで生成した静的ページが表示されるように、
リポジトリのsettingsで githubpagesの公開先を/docsに変更してください

![2017-08-08 12 53 38](https://user-images.githubusercontent.com/6639726/29055680-ce014b1a-7c38-11e7-85a1-e920579cd06b.png)

**Comment by maru877** [comment]
設定変更しました。
<img width="801" alt="2017-08-08 14 49 00" src="https://user-images.githubusercontent.com/19515445/29057972-ce209adc-7c48-11e7-9878-c15d10c79001.png">

**Comment by stmngw** [comment]
@maru877 @harada4atsushi 
設定変更ありがとうございました。
ルート相対で書いているのでスタイルがあたらず、こちらで確認いただくことはできませんでした。
申し訳ありません。
確認用は以下に用意しました。
http://mof.stm.me/
