### ISSUE TITLE
リンク設定

### ISSUE THREAD

**Issue by stmngw** [mofmof/site#5]

**Comment by stmngw** [comment]
![img_3554](https://user-image@s.githubusercontent.com/6639726/29099275-58846794-7cdf-11e7-9f4c-2095d47505c9.JPG)
@maru877 リンク先を教えてください。

**Comment by maru877** [comment]
@stmngw 
イメージが見れないので、貼り直していただいてよろしいですか？

**Comment by stmngw** [comment]
@maru877 失礼いたしました
<img width="1269" alt="2017-08-09 11 29 00" src="https://user-images.githubusercontent.com/6639726/29102730-1b4df5e0-7cf6-11e7-91b4-b90ebb3755fe.png">
http://mof.stm.me/service/

**Comment by maru877** [comment]
リンクはmyopeとshareの2つでお願いします。
(レンタルCTOとpeersは削っちゃってください)

myope
https://www.my-ope.net/

share
http://www.sharing-economy-starter.biz/

**Comment by stmngw** [comment]
@maru877 @harada4atsushi 存在するページへのリンク設定は完了
